author: Ribesg
main: ${project.groupId}.${project.artifactId}.bukkit.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number
load: STARTUP
